# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

show_icon: false # Disable the status icon
secure_input_notification: false # Disable the notifications

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  - triggers: [":->", ":ra", ":arr"]
    replace: "→"
  - triggers: [":<-", ":la"]
    replace: "←"

  - trigger: ":yes"
    replace: "✅"
  - trigger: ":no"
    replace: "🛑"
  - trigger: ":some"
    replace: "🟡"

  # Dates
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

  - trigger: ":week"
    replace: "{{output}}"
    vars:
      - name: output
        type: script
        params:
          args:
            - python
            - "%CONFIG%/scripts/week-info.py"
  
  - trigger: ":db"
    replace: "{{output}}"
    vars:
      - name: output
        type: script
        params:
          args:
            - python
            - "%CONFIG%/scripts/daily-branch.py"
